@taskkill /fi "WINDOWTITLE eq StateCenter"
@taskkill /fi "WINDOWTITLE eq Supervisor"
@taskkill /fi "WINDOWTITLE eq Worker:7081"
@taskkill /fi "WINDOWTITLE eq Worker:7082"
@taskkill /fi "WINDOWTITLE eq Merger"
@taskkill /fi "WINDOWTITLE eq Cacher"